#!/bin/sh
#echo "Gedit app starting log" > ~/ageditcvr.log
OLDIFS="$IFS"
# scripts started in an apple app container to not use the user PATH why do not know.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
apppath="`dirname $0`"
# the filelist of mac is a array of strings seperated by ", " (comma space)
# convert this to a array of strings separated by a space which is the default on bash scripting.
IFS=", "
filelist=(`osascript $apppath/../Resources/FilesSelector.scpt`)
IFS="$OLDIFS"
for I in "${filelist[@]}"
do
#We open each selected file in finder with gedit.
# Opening more script or text files at once is possible
# A selected directory will be ignored.
	if [ -f "$I" ] ; then
		exec /opt/local/bin/gedit "$I" &> /dev/null &
	else
# Yes Gedit.app is a directory but on mac the program launcher.
# It will open gedit with a new unsaved document
		if [ "Gedit.app" == "`echo $I | grep -o "Gedit.app"`" ] ; then
			exec /opt/local/bin/gedit &> /dev/null &
		fi
	fi		
done
exit
