#!/bin/sh
echo "******** Finder Selection Log ***********" > ~/FinderSelLauncher.log
OLDIFS="$IFS"
# scripts started in an apple app container do not use the user PATH into ~/.bash_profile file why do not know.
# If You want this script to start a x11 macports app for example export the full path
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
apppath="`dirname $0`"
# The return of our mac script is just a file list with a line for each selected item in finder
# First we use IFS change to new line only with a real new line return in. Works on all bashes and sh.
# We create an array . It's the best way.
# When working with complicated long file names.
# Such as a music library for example.
IFS="
"
filelist=(`osascript $apppath/../Resources/FilesSelector.applescript`)
IFS="$OLDIFS"
for I in "${filelist[@]}"
do
#We open each selected file or map in finder with : replace the echo to log file with you're desired
#commands or actions.
	if [ -f "$I" ] ; then
		#exec gedit "$I" &> /dev/null &
		echo "Selected File: $I" >> ~/FinderSelLauncher.log
	else
# Yes .app is a directory but on mac the program launcher.
		if [ ".app" == "`echo $I | grep -o ".app"`" ] ; then
			echo "The application container is: $I" >> ~/FinderSelLauncher.log
		else
			echo "Selected Map: $I" >> ~/FinderSelLauncher.log
		fi
	fi		
done
# For anti IFS Users:
# Other Bash options to read in the mac array all compliant with sh cause macos stopped the use off bash since catalina I think.
# This means that mapfile or readarray are not avbl to read in a stdin list into a array..
echo "" >> ~/FinderSelLauncher.log
echo "Next way " >> ~/FinderSelLauncher.log

s_array=()
while read -r line
do
	s_array+=("$line")
done <<<"`osascript $apppath/../Resources/FilesSelector.applescript`"

echo "Number of records in array: ${#s_array[@]}" >> ~/FinderSelLauncher.log
echo "Full array: " "${s_array[@]}" >> ~/FinderSelLauncher.log
echo "" >> ~/FinderSelLauncher.log
c=0
for K in "${s_array[@]}"
do
	echo "record `printf "%02d" $c` $K" >> ~/FinderSelLauncher.log
	let "c=c+1"
done
# Bash script  4+ version macos stopped using descent bash since Catalina or so.
# Older macos still using bash used a Hisorical bash version below 4 like High Sierra
# mapfile does not work there. But if You have a bash adapt the first rule in this script to you're bash path.

echo "" >> ~/FinderSelLauncher.log
echo "With mapfile only works in bash 4+" >> ~/FinderSelLauncher.log
#mapfile -t  t_array < <(osascript $apppath/../Resources/FilesSelector.applescript)
#echo "Number off records in array : ${#t_array[@]}" >> ~/FinderSelLauncher.log
#echo "Full array : ${t_array[@]}" >> ~/FinderSelLauncher.log
#echo "" >> ~/FinderSelLauncher.log
#c=0
#for L in "${t_array[@]}"
#do
#	echo "record `printf "%02d" $c` $L" >> ~/FinderSelLauncher.log
#	let "c=c+1"
#done

exit


